// Generated by https://quicktype.io

import { OperacionTesoreria } from "./operaciontesoreria.model";

export interface CuentaContable {
  id:                 number;
  moneda:             string;
  nombre:             string;
  numero:             string;
  operacionTesoreria: OperacionTesoreria;
  usaDocumento:       boolean;
}

